### ISSUE TITLE
LSPTextHover logs InterruptedException as error

### ISSUE THREAD

**Issue by jukzi** [eclipse-lsp4e/lsp4e#1158]
hovering
eclipse.platform.releng.aggregator\eclipse-platform-parent\pom.xml
`</link>` in line 83 in eclipse IDE results today in multiple messages logged (website seems to timeout today):
"Could not get hover region due to timeout after 1000 milliseconds", "UI freeze of 1,0s at 12:31:32.437", InterruptedException:

```
java.lang.InterruptedException
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:386)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.eclipse.lsp4e.operations.hover.LSPTextHover.getHoverInfo(LSPTextHover.java:73)
	at org.eclipse.ui.internal.genericeditor.hover.CompositeTextHover.getHoverInfo2(CompositeTextHover.java:60)
	at org.eclipse.jface.text.TextViewerHoverManager$1.run(TextViewerHoverManager.java:155)
```

https://github.com/eclipse-lsp4e/lsp4e/blob/803ae838839b3c40597118d7efab06550fc90998/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/hover/LSPTextHover.java#L77

It's bad it lags ui, its ok to warn about timeout, but the follow up InterruptedException should not be logged as error.

**Comment by jukzi** [comment]
![image](https://github.com/user-attachments/assets/903782e1-c1cd-4f56-a80e-d665aa53cf0b)

**Comment by rubenporras** [comment]
Hi @jukzi ,

I agree. I will create a PR.

**Comment by rubenporras** [comment]
Thanks for reporting the issue. I have remove the log and it will be part of the next release.

**Comment by jukzi** [comment]
thanks!
