### ISSUE TITLE
Markdown to HTML "Build must not be set"

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-lsp4e/lsp4e#577]
I sometimes see this message in the log (and HTML not rendered):
```
java.lang.IllegalStateException: Builder must not be set
	at org.eclipse.mylyn.wikitext.parser.MarkupParser.parseToHtml(MarkupParser.java:114)
	at org.eclipse.lsp4e.LSPEclipseUtils.lambda$11(LSPEclipseUtils.java:1222)
	at org.eclipse.lsp4j.jsonrpc.messages.Either.map(Either.java:75)
	at org.eclipse.lsp4e.LSPEclipseUtils.getHtmlDocString(LSPEclipseUtils.java:1211)
	at org.eclipse.lsp4e.operations.completion.LSCompletionProposal.getAdditionalProposalInfo(LSCompletionProposal.java:342)
	at org.eclipse.lsp4e.operations.completion.LSCompletionProposal.getAdditionalProposalInfo(LSCompletionProposal.java:1)
	at org.eclipse.jface.text.contentassist.AdditionalInfoController$Timer$2$1.run(AdditionalInfoController.java:116)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by sebthom** [comment]
We switched from mylyn markupparser to commonmark in the meantime.
